// EXPENSES
export const LOAD_EXPENSES = 'LOAD_EXPENSES';
export const ADD_NEW_EXPENSE = 'ADD_NEW_EXPENSE';



// REVENUES
export const LOAD_REVENUES = 'LOAD_REVENUES';
export const ADD_NEW_REVENUE = 'ADD_NEW_REVENUE';